# Generated by Django 3.1 on 2021-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20211216_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='delay',
            field=models.BooleanField(default=False, verbose_name='تاخیر'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.BooleanField(default=True, verbose_name='آیا هنوز در امانت است یا خیر؟ '),
        ),
    ]
