# Generated by Django 3.1 on 2021-12-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20211217_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='book.Category', verbose_name='دسته بندی'),
        ),
    ]
